# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: postify
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: postify
service: ResAPI

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /api/products/
          method: any
      - http:
          path: /{proxy+}
          method: any

custom:
  serverless-offline:
    httpPort: 3000
